-- EMPLOYESS (scott 계정의 emp 테이블 원본)
-- EMPLOYESS 전체 조회
SELECT * FROM EMPLOYEES e;
-- EMPLOYESS의 first_name, last_name, job_id 조회
SELECT
	FIRST_NAME,
	LAST_NAME,
	JOB_ID
FROM 
	EMPLOYEES e;

-- 사원번호가 176인 사원의 LAST_NAME,부서 번호 조회
SELECT
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	EMPLOYEE_ID = 176;

-- 연봉이 12000 이상 되는 직원들의 LAST_NAME 과 연봉 조회
SELECT
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE
	SALARY >= 12000;

-- 연봉이 5000에서 12000 범위가 아닌 사람들의 LAST_NAME과 연봉 조회
SELECT
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE 
	SALARY <5000
	OR SALARY >12000;

-- 20번 혹은 50번 부서에서 근무하는 사원들의 LAST_NAME,부서번호를 조회 단, 이름의 오름차순, 부서의 오름차순으로 정렬
SELECT
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	e.DEPARTMENT_ID IN(20, 50)
ORDER BY
	LAST_NAME ASC,
	DEPARTMENT_ID ASC; 

-- 커미션을 버는 사원들의 LAST_NAME,SALARY,COMMISSION_PCT를 조회 단, 연봉의 내림차순, 커미션 내림차순으로 정렬
SELECT
	LAST_NAME,
	SALARY,
	COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT > 0
ORDER BY
	SALARY DESC,
	COMMISSION_PCT DESC;

-- 연봉이 2500,3500,7000이 아니며 JOB_ID가 SA_REP OR SR_CLERK인 사원 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	SALARY NOT IN(2500, 3500, 700)
	AND JOB_ID IN ('SA_REP', 'ST_CLERK'); 

-- 2018/02/20 ~ 2018/05/01 사이에 고용된 직원들의 LAST_NAME,EMPLOYEE_ID,고용일자(HIRE_DATE) 조회
SELECT
	E.LAST_NAME ,
	E.EMPLOYEE_ID ,
	E.HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	E.HIRE_DATE >= '2018-02-20'
	AND E.HIRE_DATE <= '2018-05-01';

-- 2015년에 고용된 사원 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	E.HIRE_DATE >= '2015-01-01'
	AND E.HIRE_DATE <= '2015-12-31' ;
	

-- 20번 혹은 50번 부서에서 근무하며, 연봉이 5000~ 12000 사이인 직원들의 FIRST_NAME,LAST_NAME,연봉조회(오름차순)
SELECT
	FIRST_NAME,
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE
	E.DEPARTMENT_ID IN(20, 50)
	AND SALARY BETWEEN 5000 AND 12000
ORDER BY
	SALARY ASC;

-- 연봉이 5000~12000사이가 아닌 직원들의 정보 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	SALARY NOT BETWEEN 5000 AND 12000;

-- BETWEEN A AND B로 변경
-- 2018/02/20 ~ 2018/05/01 사이에 고용된 직원들의 LAST_NAME,EMPLOYEE_ID,고용일자(HIRE_DATE) 조회
SELECT
	E.LAST_NAME ,
	E.EMPLOYEE_ID ,
	E.HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	E.HIRE_DATE BETWEEN '2018-02-20'
	AND '2018-05-01';


-- LAST_NAME 에 u가 포함되는 사원들의 사번, LAST_NAME 조회
SELECT
	LAST_NAME,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	LAST_NAME LIKE '%u%';

-- LAST_NAME 의 네 번째 글자가 a인 사원들의 사번, LAST_NAME 조회
SELECT
	LAST_NAME,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	LAST_NAME LIKE '___a%';

-- LAST_NAME 에 a 혹은 e 글자가 포함되는 사원들의 사번, LAST_NAME 조회(단, LAST_NAME오름차순)
SELECT
	LAST_NAME,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	LAST_NAME LIKE '%a%'
	OR LAST_NAME LIKE '%e%'
ORDER BY
	LAST_NAME ASC;

-- LAST_NAME 에 a 와 e 글자가 포함되는 사원들의 사번, LAST_NAME 조회(단, LAST_NAME오름차순)
SELECT
	LAST_NAME,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	LAST_NAME LIKE '%a%'
	and LAST_NAME LIKE '%e%'
--WHERE
	--LAST_NAME LIKE '%a%e%'
	--or LAST_NAME LIKE '%a%e%'
ORDER BY
	LAST_NAME ASC;


-- MANAGER_ID 가 없는 사원들의 LAST_NAME 및 JOB_ID 조회
SELECT
	E.LAST_NAME,
	E.JOB_ID
FROM
	EMPLOYEES e
WHERE
	MANAGER_ID IS NULL;

-- JOB_ID가 ST_CLERK가 아닌 사원이 없는 부서 조회 단, 부서 번호가 NULL인 경우는 제외한다.
SELECT
	DISTINCT E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	JOB_ID NOT IN ('ST_CLERK')
	AND E.DEPARTMENT_ID IS NOT NULL;

-- COMMISSION_PCT가 NULL 이 아닌 사원들 중에서 COMMISION = SALARY * COMMISION_PCT를 구한다. 사원번호,FIRST_NAME,JOB_ID와 함께 조회
SELECT
	E.EMPLOYEE_ID ,
	E.FIRST_NAME ,
	E.JOB_ID,
	E.SALARY *E.COMMISSION_PCT AS COMMISION
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT IS NOT NULL; 